#!/usr/bin/env node
// Copies the deploy-ready Flutter phone into phone/<version>/ and points the
// page at it. Builds nothing: run `node scripts/build-deploy.mjs` in the phone
// repo first (see README.md).
//
//   node scripts/sync-phone.mjs [path-to-phone-dist]      default ../tabby-phone-flutter/dist
//
// - keeps every file a browser can request, including the JS + CanvasKit
//   fallback variants Flutter picks itself when WasmGC is missing;
// - drops what the page never fetches: .br/.gz siblings (the host compresses),
//   source maps, symbols, the phone repo's own host.html/index.html, the
//   service worker (the bootstrap never registers it) and version.json;
// - puts the files under phone/<content hash>/, so the folder name changes
//   whenever the build does and every file inside can be cached forever;
// - writes assets/phone-version.js (window.PHONE_BASE), the one place the page
//   learns that path. Old phone/<hash>/ folders are removed.
//
// phone/ IS COMMITTED, on purpose: a plain static deploy of this repo then
// works with no build step. The cost is roughly 20 MB of binary in git.

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { brotliCompressSync, constants, gzipSync } from 'node:zlib';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = resolve(process.argv[2] || join(ROOT, '..', 'tabby-phone-flutter', 'dist'));
const OUT = join(ROOT, 'phone');

if (!existsSync(join(SRC, 'main.dart.js'))) {
  console.error(`No Flutter build at ${SRC}. Run "node scripts/build-deploy.mjs" in the phone repo first.`);
  process.exit(1);
}

const DROP = [/\.(br|gz|map|symbols)$/, /^(host|index)\.html$/, /^version\.json$/, /^flutter_service_worker\.js$/];
const walk = (d) => readdirSync(d, { withFileTypes: true }).flatMap((e) =>
  e.isDirectory() ? walk(join(d, e.name)) : [join(d, e.name)]);
const relOf = (base, f) => relative(base, f).split(sep).join('/');

// Text files are copied with LF line endings whatever the build machine wrote,
// so the hash (and every clone, on any OS) sees the same bytes. Binaries as is.
const TEXT = /\.(js|mjs|json|html|css|txt|svg)$|NOTICES$/;
const bytes = (r) => {
  const b = readFileSync(join(SRC, r));
  return TEXT.test(r) ? Buffer.from(b.toString('utf8').replace(/\r\n/g, '\n'), 'utf8') : b;
};

const files = walk(SRC).map((f) => relOf(SRC, f)).filter((r) => !DROP.some((re) => re.test(r))).sort();
const hash = createHash('sha256');
for (const r of files) hash.update(r + '\0').update(bytes(r));
const version = hash.digest('hex').slice(0, 10);

mkdirSync(OUT, { recursive: true });
for (const d of readdirSync(OUT)) rmSync(join(OUT, d), { recursive: true, force: true });
const dest = join(OUT, version);
for (const r of files) {
  mkdirSync(dirname(join(dest, r)), { recursive: true });
  writeFileSync(join(dest, r), bytes(r));
}
writeFileSync(
  join(ROOT, 'assets', 'phone-version.js'),
  `// Generated by scripts/sync-phone.mjs. Do not edit.\nwindow.PHONE_BASE = 'phone/${version}/';\n`
);

let raw = 0, gz = 0, br = 0;
const rows = [];
for (const r of files) {
  const body = readFileSync(join(dest, r));
  const packed = /\.(woff2|png)$/.test(r);
  const g = packed ? body.length : gzipSync(body, { level: 9 }).length;
  const b = packed ? body.length : brotliCompressSync(body, { params: { [constants.BROTLI_PARAM_QUALITY]: 11 } }).length;
  raw += body.length; gz += g; br += b;
  rows.push([r, body.length, g, b]);
}
const kb = (n) => (n / 1024).toFixed(1).padStart(9) + ' KB';
console.log('file'.padEnd(46) + 'raw'.padStart(12) + 'gzip'.padStart(12) + 'brotli'.padStart(12));
for (const r of rows.sort((a, b) => b[1] - a[1]).slice(0, 12)) console.log(r[0].padEnd(46) + kb(r[1]) + kb(r[2]) + kb(r[3]));
console.log(`... ${rows.length} files in all`);
console.log('total in phone/'.padEnd(46) + kb(raw) + kb(gz) + kb(br));
console.log(`\nphone/${version}/ ready; assets/phone-version.js updated. Commit both.`);
